/**
 * 拼音工具 - 用于平台编码生成
 * 编码规则：PT-XX，XX为平台简称的首字母，如有首字母重复的，平台简称第一个字用全拼
 */

const INITIALS = 'ABCDEFGHJKLMNOPQRSTWXYZ';
const BOUNDARIES = '阿八嚓哒鹅发旮哈讥咔垃妈拿噢啪七日撒他挖希压匝';

/** 获取汉字的拼音首字母 */
export function getPinyinInitial(char: string): string {
  const ch = char.charAt(0);
  if (/[a-zA-Z]/.test(ch)) return ch.toUpperCase();
  if (!/[\u4e00-\u9fff]/.test(ch)) return '';

  for (let i = BOUNDARIES.length - 1; i >= 0; i--) {
    if (ch.localeCompare(BOUNDARIES[i], 'zh') >= 0) {
      return INITIALS[i];
    }
  }
  return '';
}

/** 拼音数据源：拼音 -> 常用汉字 */
const PINYIN_SOURCE: Record<string, string> = {
  a: '阿啊',
  ai: '哎唉爱矮碍艾哀癌挨蔼隘',
  an: '安暗岸按案谙鞍氨庵黯',
  ang: '昂盎',
  ao: '凹奥傲熬袄澳懊',
  ba: '八把爸巴拔霸吧坝罢芭疤扒叭靶',
  bai: '白百摆败拜柏佰',
  ban: '半班般办版伴搬板扮拌绊瓣斑',
  bang: '帮邦旁榜膀绑棒磅蚌傍',
  bao: '包宝保报抱暴薄爆堡饱曝豹鲍',
  bei: '北被备倍背辈杯贝悲碑卑惫',
  ben: '本奔笨',
  beng: '崩绷蹦迸',
  bi: '比必笔闭避壁臂逼彼碧毕币庇痹弊蔽',
  bian: '边变便遍辨辩编扁贬鞭匾',
  biao: '表标彪镖裱飚',
  bie: '别憋',
  bin: '宾滨彬斌濒殡',
  bing: '并兵冰丙饼炳病',
  bo: '波博播伯拨勃搏薄驳泊柏帛渤',
  bu: '不步布部补捕卜哺',
  ca: '擦嚓',
  cai: '才采彩财菜猜裁材踩',
  can: '参残餐灿惨蚕',
  cang: '仓苍藏沧舱',
  cao: '草操曹糙槽',
  ce: '策侧册厕',
  ceng: '层曾蹭',
  cha: '查差插察茶叉茬碴',
  chai: '拆柴',
  chan: '产缠禅颤铲蝉馋掺',
  chang: '长常厂场唱畅倡昌尝偿肠',
  chao: '超朝潮吵抄巢钞',
  che: '车彻撤扯澈',
  chen: '陈晨沉称尘衬臣辰趁忱',
  cheng: '成城程承称乘呈惩橙诚撑秤',
  chi: '持吃尺迟池翅耻齿侈驰',
  chong: '冲充崇虫宠重',
  chou: '抽筹仇愁丑臭稠绸酬',
  chu: '出处初除楚触储厨础畜',
  chuan: '川穿传船串喘',
  chuang: '创窗床闯',
  chui: '吹炊垂锤捶',
  chun: '春纯醇唇蠢',
  ci: '此次词辞慈瓷刺茨',
  cong: '从丛聪葱匆',
  cu: '促粗醋簇',
  cuan: '窜篡蹿',
  cui: '催脆翠摧淬',
  cun: '村存寸',
  cuo: '错措挫搓',
  da: '达答打大',
  dai: '代带待大戴袋贷怠呆逮',
  dan: '单但担旦蛋淡弹胆丹诞',
  dang: '当党档挡荡',
  dao: '到道导岛倒刀稻蹈盗悼',
  de: '的得德',
  deng: '灯等登邓凳瞪',
  di: '地第低底抵弟帝递滴迪敌堤',
  dian: '电点店典垫殿淀碘',
  diao: '调掉吊钓雕',
  die: '跌叠碟蝶迭',
  ding: '定顶丁盯钉鼎',
  dong: '东动懂冬董冻洞栋',
  dou: '都斗豆抖逗兜',
  du: '度读都独毒渡堵赌杜肚妒',
  duan: '端段短断缎锻',
  dui: '对队堆兑',
  dun: '顿吨蹲敦盾钝',
  duo: '多朵夺躲堕舵剁',
  e: '鹅额俄恶饿恩蛾厄',
  er: '而二耳儿尔',
  fa: '发法罚伐乏阀',
  fan: '反翻凡烦繁饭范贩帆返藩樊',
  fang: '方放房防访仿纺芳',
  fei: '非飞费肥废菲肺匪沸啡',
  fen: '分份纷奋愤粉芬坟焚',
  feng: '风丰封锋逢缝疯蜂峰讽凤',
  fo: '佛',
  fou: '否',
  fu: '服付复府副负富福父妇附符腐赴浮扶幅辅伏傅覆俯斧缚',
  ga: '旮嘎',
  gai: '改该盖概钙溉',
  gan: '干感赶敢甘肝杆柑竿',
  gang: '刚钢港岗纲缸杠',
  gao: '高搞告稿糕膏',
  ge: '个各哥歌格革隔阁葛割铬',
  gei: '给',
  gen: '跟根',
  geng: '更耕',
  gong: '工公共供功攻宫弓恭贡',
  gou: '够构购狗钩沟苟',
  gu: '古故顾鼓骨估谷股固孤雇',
  gua: '挂瓜刮寡卦',
  guai: '怪拐乖',
  guan: '关管观官馆惯冠贯灌罐',
  guang: '光广逛',
  gui: '规归贵鬼桂柜跪硅',
  gun: '滚棍',
  guo: '过国果锅裹郭',
  ha: '哈蛤',
  hai: '还海害孩嗨',
  han: '含寒汉韩函旱喊罕翰',
  hang: '航行杭',
  hao: '好号毫豪耗浩壕',
  he: '和合何河核贺喝赫荷鹤',
  hei: '黑嘿',
  hen: '很恨狠',
  heng: '横衡哼',
  hong: '红宏洪轰虹鸿烘',
  hou: '后厚侯喉吼候',
  hu: '和湖呼胡虎护互户忽壶狐糊蝴',
  hua: '话花化画华划滑哗桦',
  huai: '坏怀淮',
  huan: '还换欢环患幻缓唤焕',
  huang: '黄皇荒晃慌煌恍簧',
  hui: '会回辉汇毁灰挥慧绘惠恢贿',
  hun: '混婚魂昏浑荤',
  huo: '活或火伙货获祸惑霍',
  ji: '机几及级极即集记技计际继纪急击激既积基迹忌剂寂祭吉脊籍辑',
  jia: '家加假价甲佳驾嫁架嘉',
  jian: '见间建件检减简尖坚肩键健渐兼监煎剪捡荐剑鉴践',
  jiang: '将讲江姜降奖酱疆僵桨',
  jiao: '叫教交角脚较觉娇搅焦胶郊骄浇',
  jie: '结解接节界截姐届介阶借戒竭洁捷',
  jin: '进今金近紧尽仅斤禁锦筋津晋',
  jing: '经京精竞景静惊井晶镜敬境警净径',
  jiong: '窘',
  jiu: '就九旧久救酒纠究揪',
  ju: '局举具据距句聚拒居剧巨惧锯',
  juan: '卷捐倦圈绢',
  jue: '决绝觉掘爵诀',
  jun: '军均君菌俊',
  ka: '卡咖喀',
  kai: '开凯慨楷',
  kan: '看砍堪勘坎',
  kang: '抗康扛炕慷',
  kao: '考靠烤拷',
  ke: '可科克客刻课颗渴柯棵壳',
  ken: '肯啃垦恳',
  keng: '坑',
  kong: '空控孔恐',
  kou: '口扣寇抠',
  ku: '苦哭库酷枯',
  kua: '跨夸垮挎',
  kuai: '快块筷',
  kuan: '宽款',
  kuang: '况矿框狂旷眶',
  kui: '亏愧溃奎魁馈',
  kun: '困昆捆坤',
  kuo: '扩括阔廓',
  la: '拉啦垃辣蜡喇',
  lai: '来赖莱',
  lan: '兰蓝烂栏懒拦篮滥澜',
  lang: '郎浪朗狼廊',
  lao: '老劳牢捞烙姥',
  le: '了乐勒',
  lei: '类雷累泪蕾擂',
  leng: '冷愣',
  li: '力理里立利李离历礼例丽粒励黎梨厘隶',
  lia: '俩',
  lian: '连联脸练恋链莲廉怜帘炼',
  liang: '两量亮梁凉粮良辆晾',
  liao: '了料聊疗辽廖撩',
  lie: '列烈猎裂劣',
  lin: '林临邻淋麟磷鳞',
  ling: '领另令零灵铃龄凌陵岭',
  liu: '六留流刘柳溜',
  long: '龙隆笼聋弄拢楼',
  lou: '楼漏露搂陋',
  lu: '路录露律旅绿率陆炉鹿鲁卢芦碌',
  luan: '乱卵',
  lue: '略掠',
  lun: '论轮伦沦',
  luo: '落罗络洛螺骆逻',
  ma: '妈马吗嘛麻骂码蚂',
  mai: '买卖迈麦埋脉',
  man: '满慢漫曼蛮瞒蔓',
  mang: '忙茫盲芒',
  mao: '毛冒猫贸帽矛茅貌',
  me: '么',
  mei: '没美每妹眉媒煤霉梅魅',
  men: '们门闷',
  meng: '梦猛蒙盟萌锰朦',
  mi: '米密迷蜜秘觅靡',
  mian: '面免棉绵眠勉缅',
  miao: '秒苗描庙妙渺',
  mie: '灭蔑',
  min: '民敏闽闵',
  ming: '名明命鸣铭冥',
  miu: '谬',
  mo: '没末莫模磨默魔抹墨摩膜漠',
  mou: '某谋牟',
  mu: '目木母亩幕墓牧慕暮牡募',
  na: '那拿哪纳钠娜',
  nai: '奶乃耐奈',
  nan: '南男难',
  nang: '囊',
  nao: '闹脑恼挠',
  ne: '呢',
  nei: '内',
  nen: '嫩',
  neng: '能',
  ni: '你泥尼拟逆匿腻妮',
  nian: '年念粘碾',
  niang: '娘酿',
  niao: '鸟尿',
  nie: '捏镍涅',
  nin: '您',
  ning: '宁凝拧柠泞',
  niu: '牛纽扭',
  nong: '农浓弄',
  nu: '怒奴努',
  nv: '女',
  nuan: '暖',
  nuo: '诺挪懦',
  ou: '欧偶鸥呕耦',
  pa: '怕爬帕趴扒',
  pai: '排拍派牌迫',
  pan: '盘判盼攀叛潘',
  pang: '旁胖庞',
  pao: '跑炮泡抛袍',
  pei: '配陪赔佩培沛',
  pen: '盆喷',
  peng: '碰朋捧棚蓬膨鹏',
  pi: '批皮匹劈疲屁僻脾',
  pian: '片篇偏骗便',
  piao: '票飘漂瓢',
  pin: '品贫频拼',
  ping: '平评瓶凭萍屏',
  po: '破坡泼颇婆迫魄',
  pou: '剖',
  pu: '普铺朴浦葡仆莆',
  qi: '起其气七期器齐奇骑棋旗企启契砌',
  qia: '恰卡掐',
  qian: '前千钱签浅迁牵潜欠谦乾遣',
  qiang: '强枪墙抢腔呛',
  qiao: '桥巧敲瞧俏窍翘',
  qie: '切且怯窃',
  qin: '亲琴侵秦勤芹擒',
  qing: '清青轻情请庆晴倾氢',
  qiong: '穷琼',
  qiu: '求球秋丘囚',
  qu: '去取区曲趣驱屈渠',
  quan: '全权圈劝泉拳券',
  que: '却确缺雀鹊',
  qun: '群裙',
  ran: '然染燃',
  rang: '让嚷壤',
  rao: '绕扰饶',
  re: '热惹',
  ren: '人认任仁忍韧',
  reng: '仍扔',
  ri: '日',
  rong: '容融荣溶蓉绒熔',
  rou: '肉柔揉',
  ru: '如入儒乳辱',
  ruan: '软',
  rui: '瑞锐蕊',
  run: '润闰',
  ruo: '若弱',
  sa: '撒洒萨',
  sai: '赛塞腮',
  san: '三散伞',
  sang: '桑丧嗓',
  sao: '扫骚嫂',
  se: '色涩瑟',
  sen: '森',
  sha: '杀沙纱傻啥煞',
  shai: '晒筛',
  shan: '山善闪衫扇删珊',
  shang: '上商伤赏尚',
  shao: '少烧绍哨稍勺韶',
  she: '社设射涉舌蛇奢赦',
  shen: '什深身神审甚申伸慎渗',
  sheng: '生声胜省升圣剩牲绳',
  shi: '是时使事十实世市石师识史施示式食失适室诗释氏',
  shou: '手受收首守授寿售瘦兽',
  shu: '书数术树属输束叔述熟疏署鼠舒',
  shua: '刷耍',
  shuai: '帅摔衰甩',
  shuan: '栓拴',
  shuang: '双爽霜',
  shui: '水谁睡税',
  shun: '顺瞬舜',
  shuo: '说硕朔',
  si: '四思斯丝死司私似寺撕肆',
  song: '送松宋颂诵耸',
  sou: '搜艘嗽叟',
  su: '速苏素俗诉宿缩塑肃溯',
  suan: '算酸蒜',
  sui: '随虽岁碎穗遂髓',
  sun: '孙损笋',
  suo: '所索锁缩梭',
  ta: '他她它塔踏塌',
  tai: '太台态泰抬胎',
  tan: '谈探弹叹摊贪滩瘫坛',
  tang: '堂唐糖汤躺趟烫塘',
  tao: '套讨逃桃陶淘涛',
  te: '特',
  teng: '腾疼藤',
  ti: '提体题替踢惕剃',
  tian: '天田添填甜',
  tiao: '条跳调挑',
  tie: '铁贴帖',
  ting: '听停庭挺厅亭',
  tong: '同通统痛铜桶筒童',
  tou: '头投透偷',
  tu: '土图突途涂吐兔屠',
  tuan: '团',
  tui: '推退腿',
  tun: '吞屯',
  tuo: '拖脱托驼椭妥',
  wa: '挖哇蛙瓦洼',
  wai: '外歪',
  wan: '万完晚碗玩弯湾丸挽',
  wang: '王往网望忘旺汪亡',
  wei: '为位未维伟围微威危尾卫委违韦唯味喂胃畏慰',
  wen: '问文闻温稳吻纹蚊',
  weng: '翁嗡',
  wo: '我握窝卧沃蜗',
  wu: '五无物武务误舞吴悟乌巫捂',
  xi: '西系希息习细席喜析洗吸稀溪戏膝锡惜',
  xia: '下吓虾瞎侠峡夏狭霞',
  xian: '先现线限县鲜仙险显献闲陷宪纤',
  xiang: '想向相象响香乡详项巷享像',
  xiao: '小笑校消效销晓肖萧潇',
  xie: '写些谢协鞋血械斜歇携泄',
  xin: '新心信芯辛薪欣',
  xing: '行性形星型姓幸醒兴杏刑',
  xiong: '雄兄胸凶熊',
  xiu: '修秀休锈袖绣嗅',
  xu: '需许续须虚序蓄绪叙恤',
  xuan: '选宣悬旋玄',
  xue: '学雪血穴靴',
  xun: '寻训巡迅讯询熏',
  ya: '压呀牙亚雅鸭崖衙',
  yan: '言眼研严烟沿验演颜盐炎岩延掩宴雁',
  yang: '样阳养洋扬仰氧羊杨痒漾',
  yao: '要药摇遥腰咬钥耀姚',
  ye: '也业夜叶野页液爷耶',
  yi: '一以已意义易亿移衣益亦异艺抑役忆伊',
  yin: '因引银印音隐饮阴吟',
  ying: '应营影英迎映硬盈赢颖鹰',
  yo: '哟',
  yong: '用永拥勇涌泳庸雍',
  you: '有又由油游右友优幽悠尤',
  yu: '于与余鱼雨玉语预域育欲御宇郁愈誉浴寓',
  yuan: '元原员远院圆源愿缘援园',
  yue: '月越约跃阅岳乐曰',
  yun: '运云允韵孕匀蕴',
  za: '杂扎砸匝',
  zai: '在再载灾栽宰',
  zan: '咱赞暂攒',
  zang: '脏葬赃',
  zao: '早造遭糟灶燥凿',
  ze: '则责择泽',
  zei: '贼',
  zen: '怎',
  zeng: '增曾赠',
  zha: '扎炸眨闸栅渣',
  zhai: '窄宅摘寨',
  zhan: '站战展占斩沾崭',
  zhang: '长张章掌丈帐涨仗障彰',
  zhao: '找照招朝赵罩兆',
  zhe: '这着者折哲遮',
  zhen: '真镇阵针珍振震枕侦',
  zheng: '正政整争征证蒸挣睁',
  zhi: '之只知制直至指值治支志执植职止纸质',
  zhong: '中种重众终钟忠肿仲',
  zhou: '周州洲舟粥轴皱骤',
  zhu: '主住注助猪竹祝著驻柱筑逐',
  zhua: '抓',
  zhuan: '转专砖赚',
  zhuang: '装壮撞状桩',
  zhui: '追坠缀',
  zhun: '准',
  zhuo: '捉桌着琢卓酌',
  zi: '子自字紫资仔姿滋',
  zong: '总纵宗综棕踪',
  zou: '走奏邹',
  zu: '组足族阻祖租',
  zuan: '钻',
  zui: '最嘴醉罪',
  zun: '尊遵',
  zuo: '做作坐左座昨',
};

/** 反向查找表：汉字 -> 拼音 */
const PINYIN_MAP: Record<string, string> = {};
for (const [pinyin, chars] of Object.entries(PINYIN_SOURCE)) {
  for (const ch of chars) {
    if (!PINYIN_MAP[ch]) {
      PINYIN_MAP[ch] = pinyin;
    }
  }
}

/** 获取汉字的完整拼音，找不到时回退到首字母小写 */
export function getFullPinyin(char: string): string {
  const ch = char.charAt(0);
  if (/[a-zA-Z]/.test(ch)) return ch.toLowerCase();
  if (!/[\u4e00-\u9fff]/.test(ch)) return '';
  return PINYIN_MAP[ch] || getPinyinInitial(ch).toLowerCase();
}

/**
 * 生成平台编码
 * 规则：PT-XX，XX为平台简称的首字母
 * 如有首字母重复（编码冲突），平台简称第一个字用全拼
 */
export function generatePlatformCode(shortName: string, existingCodes: string[]): string {
  if (!shortName) return 'PT-';

  const chars = Array.from(shortName);

  // 提取每个字的首字母
  const initials = chars.map(ch => getPinyinInitial(ch)).filter(Boolean).join('');
  const baseCode = `PT-${initials}`;

  // 检查是否冲突
  if (!existingCodes.includes(baseCode)) {
    return baseCode;
  }

  // 冲突时，第一个字用全拼，其余用首字母
  const firstFull = getFullPinyin(chars[0]);
  const restInitials = chars.slice(1).map(ch => getPinyinInitial(ch)).filter(Boolean).join('');
  return `PT-${firstFull}${restInitials}`.toUpperCase();
}
